### ISSUE TITLE
Requesting review 

### ISSUE THREAD

**Issue by benjp009** [benjp009/benjamin-patin-portfolio-2021#9]
# Week 3 Day 1 : Portfolio: application deploy

Dear Micronaut Reviewer :) 
This Issue is to request a review of the [Portfolio: application deploy](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/5_deploy.md). 

I have tried to add a link to me README file on the submission page, but couldn't, so I created an issue instead to solve it. 

You can review my [README file ](https://github.com/benjp009/benjamin-patin-portfolio-2021/blob/main/README.md) and my [LIVE PAGE](https://benjp009.github.io/benjamin-patin-portfolio-2021/) directly by clicking on them. 

Let me know if there is anything else you would need to achieve this task. 

Thank you

**Comment by fernandorpm** [comment]
# :heavy_check_mark: Pull Request Approved! :heavy_check_mark:
WOW WHAT IS THIS PERFECTION??????? WERE HUMANS SUPPOSED TO BEHOLD SUCH POWER????

Congratulations on your hard work! Please remember to merge the project and don't forget that you're awesome! :heart:

<img src="https://i.imgur.com/gOjmIlL.gif" width="300px" />

- You have done a wonderful job on this project! To highlight:
  - you have demonstrated great skills in following the template :heavy_check_mark: 
  - you have paid attention to almost all of the details :heavy_check_mark: 
  - you have written a nice and clean code :heavy_check_mark: 
  - your PR is on point :ok_hand: :heavy_check_mark: 

> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Just keep in mind that Microverse has a standard for the project requirements, to guarantee that you will be able to become a great developer, and both you and I have to follow them!

___
Cheers and Happy Coding! :heart:

> *As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).*

**Comment by benjp009** [comment]
@fernandorpm Thank you for your review :) 
So excited to keep on going :)
